spring:
  application:
    name: sample-api
  profiles:
    active: dev
  config:
    import: configserver:http://35.86.232.118:8888
management:
  endpoints:
    web:
      exposure:
        include: refresh